
import sys

filepath = r'c:/Users/Fabio/Desktop/SistemaPonto/src/pages/AdminDashboard.jsx'

with open(filepath, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find the end of the settings form (last occurrence of Salvar Perfil)
found_index = -1
for i in range(len(lines)):
    if 'Salvar Perfil' in lines[i] and '</button>' in lines[i+1]:
        found_index = i + 2 # Pointing to </form>
        break

if found_index != -1:
    new_tail = lines[:found_index]
    new_tail.extend([
        '                                    </form>\n',
        '                                </div>\n',
        '                            </div>\n',
        '                        </div>\n',
        '                    </div>\n',
        '                )}\n',
        '            </main>\n',
        '\n',
        '            {/* MODAL DE CONFIGURAÇÃO INICIAL DA EMPRESA (BLOQUEANTE) */}\n',
        '            {showCompanySetup && (\n',
        '                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/95 backdrop-blur-md p-4 animate-fade-in">\n',
        '                    <div className="bg-gray-900 border border-emerald-500/30 w-full max-w-2xl max-h-[90vh] overflow-y-auto shadow-[0_0_50px_rgba(16,185,129,0.1)] rounded-sm relative">\n',
        '                        <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-emerald-500 to-transparent animate-pulse"></div>\n',
        '                        <div className="bg-emerald-500/10 border-b border-emerald-500/20 p-8 text-center">\n',
        '                            <h2 className="text-2xl font-black text-white uppercase tracking-tighter flex items-center justify-center gap-3 mb-2">\n',
        '                                <span className="text-emerald-500 animate-bounce">⚡</span> Configuração _Inicial\n',
        '                            </h2>\n',
        '                            <p className="text-[10px] text-emerald-500/60 font-mono uppercase tracking-[0.2em]">\n',
        '                                Identificação da Organização Obrigatória\n',
        '                            </p>\n',
        '                        </div>\n',
        '\n',
        '                        <form onSubmit={handleSaveCompany} className="p-8 space-y-8">\n',
        '                            <div className="bg-emerald-500/5 p-6 border border-emerald-500/20 rounded-sm">\n',
        '                                <label className="block text-[10px] font-black text-emerald-500 uppercase tracking-[0.2em] mb-2 text-center">Seu Código de Acesso Corporativo</label>\n',
        '                                <div className="text-4xl font-mono text-white font-black tracking-widest text-center select-all">\n',
        '                                    {currentCompany?.loginCode || "GERADO APÓS SALVAR"}\n',
        '                                </div>\n',
        '                                <p className="text-[9px] text-gray-500 mt-3 text-center uppercase tracking-widest">Este código vinculará todos os seus colaboradores</p>\n',
        '                            </div>\n',
        '                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">\n',
        '                                <div>\n',
        '                                    <label className="block text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] mb-2 pl-1">Nome Fantasia</label>\n',
        '                                    <input\n',
        '                                        type="text"\n',
        '                                        required\n',
        '                                        className="w-full bg-white/5 border border-white/10 p-4 focus:border-emerald-500 outline-none text-white font-mono text-sm uppercase transition-all"\n',
        '                                        placeholder="MINHA ORGANIZAÇÃO LTDA"\n',
        '                                        value={companyForm.name}\n',
        '                                        onChange={(e) => setCompanyForm({ ...companyForm, name: e.target.value })}\n',
        '                                    />\n',
        '                                </div>\n',
        '                                <div>\n',
        '                                    <label className="block text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] mb-2 pl-1">CNPJ</label>\n',
        '                                    <input\n',
        '                                        type="text"\n',
        '                                        maxLength={18}\n',
        '                                        value={companyForm.cnpj || \'\'}\n',
        '                                        onChange={(e) => setCompanyForm({ ...companyForm, cnpj: formatCNPJ(e.target.value) })}\n',
        '                                        className="w-full bg-white/5 border border-white/10 p-4 focus:border-emerald-500 outline-none text-white font-mono text-sm uppercase transition-all"\n',
        '                                        placeholder="00.000.000/0001-00"\n',
        '                                    />\n',
        '                                </div>\n',
        '                            </div>\n',
        '                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">\n',
        '                                <div>\n',
        '                                    <label className="block text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] mb-2 pl-1">Telefone Contato</label>\n',
        '                                    <input\n',
        '                                        type="tel"\n',
        '                                        className="w-full bg-white/5 border border-white/10 p-4 focus:border-emerald-500 outline-none text-white font-mono text-sm uppercase transition-all"\n',
        '                                        placeholder="(11) 99999-9999"\n',
        '                                        value={companyForm.phone}\n',
        '                                        onChange={(e) => setCompanyForm({ ...companyForm, phone: e.target.value })}\n',
        '                                    />\n',
        '                                </div>\n',
        '                                <div>\n',
        '                                    <label className="block text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] mb-2 pl-1">Regime de Trabalho</label>\n',
        '                                    <select\n',
        '                                        className="w-full bg-white/5 border border-white/10 p-4 focus:border-emerald-500 outline-none text-white font-mono text-sm uppercase transition-all"\n',
        '                                        value={companyForm.workSchedule}\n',
        '                                        onChange={(e) => setCompanyForm({ ...companyForm, workSchedule: e.target.value })}\n',
        '                                    >\n',
        '                                        <option value="monday_friday" className="bg-gray-900">Segunda a Sexta (5x2)</option>\n',
        '                                        <option value="monday_saturday" className="bg-gray-900">Segunda a Sábado (6x1)</option>\n',
        '                                        <option value="12x36" className="bg-gray-900">Escala 12x36</option>\n',
        '                                    </select>\n',
        '                                </div>\n',
        '                            </div>\n',
        '                            <div className="space-y-4">\n',
        '                                <label className="block text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] mb-2 pl-1">Localização de Referência para Geofencing</label>\n',
        '                                <div className="grid grid-cols-2 gap-4">\n',
        '                                    <input\n',
        '                                        type="number"\n',
        '                                        step="any"\n',
        '                                        placeholder="LATITUDE"\n',
        '                                        className="w-full bg-white/5 border border-white/10 p-3 focus:border-emerald-500 outline-none font-mono text-xs text-white"\n',
        '                                        value={companyForm.latitude}\n',
        '                                        onChange={e => setCompanyForm({ ...companyForm, latitude: e.target.value })}\n',
        '                                    />\n',
        '                                    <input\n',
        '                                        type="number"\n',
        '                                        step="any"\n',
        '                                        placeholder="LONGITUDE"\n',
        '                                        className="w-full bg-white/5 border border-white/10 p-3 focus:border-emerald-500 outline-none font-mono text-xs text-white"\n',
        '                                        value={companyForm.longitude}\n',
        '                                        onChange={e => setCompanyForm({ ...companyForm, longitude: e.target.value })}\n',
        '                                    />\n',
        '                                </div>\n',
        '                                <button\n',
        '                                    type="button"\n',
        '                                    onClick={() => {\n',
        '                                        if (navigator.geolocation) {\n',
        '                                            navigator.geolocation.getCurrentPosition(pos => {\n',
        '                                                setCompanyForm({\n',
        '                                                    ...companyForm,\n',
        '                                                    latitude: pos.coords.latitude,\n',
        '                                                    longitude: pos.coords.longitude\n',
        '                                                });\n',
        '                                            });\n',
        '                                        } else {\n',
        '                                            alert("Geolocalização não suportada.");\n',
        '                                        }\n',
        '                                    }}\n',
        '                                    className="w-full py-3 bg-emerald-500/10 text-emerald-500 text-[9px] font-black uppercase tracking-widest border border-emerald-500/20 hover:bg-emerald-500 hover:text-black transition-all flex items-center justify-center gap-2"\n',
        '                                >\n',
        '                                    🎯 Capturar Minha Localização Atual\n',
        '                                </button>\n',
        '                            </div>\n',
        '                            <button\n',
        '                                type="submit"\n',
        '                                disabled={isSavingSettings}\n',
        '                                className="w-full py-5 bg-emerald-600 text-black font-black text-xs uppercase tracking-[0.3em] hover:bg-emerald-500 transition-all shadow-[0_0_30px_rgba(16,185,129,0.4)] hover:shadow-[0_0_50px_rgba(16,185,129,0.6)] relative overflow-hidden group"\n',
        '                            >\n',
        '                                {isSavingSettings ? \'CONFIGURANDO...\' : \'FINALIZAR CONFIGURAÇÃO\'}\n',
        '                                <div className="absolute inset-0 bg-white/20 translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-500 skew-x-12"></div>\n',
        '                            </button>\n',
        '                        </form>\n',
        '                    </div>\n',
        '                </div>\n',
        '            )}\n',
        '        </div>\n',
        '    </div>\n',
        '    );\n',
        '};\n',
        '\n',
        'export default AdminDashboard;\n'
    ])
    
    with open(filepath, \'w\', encoding=\'utf-8\') as f:
        f.writelines(new_tail)
    print("FINAL TAIL RECONSTRUCTION COMPLETE")
else:
    print("SETTINGS FORM NOT FOUND")
